# Problem 25: 1000-digit Fibonacci Number

# create list with fibonacci numbers

condition_lenght = 1000

fibo_lst = [1, 1] # starts with 1 and 1

for i in range(10000):
    term = fibo_lst[i] + fibo_lst[i+1] # each new term is generated by adding the previous term
    if len(str(term)) < condition_lenght:
        fibo_lst.append(term)
    if len(str(term)) == condition_lenght:
        fibo_lst.append(term)
        break

print(fibo_lst[-1])
print(len(str(fibo_lst[-1])))
print(fibo_lst.index(fibo_lst[-1]))
print(len(fibo_lst))
