# Problem 2: Even Fibonacci Numbers

# create list with fibonacci numbers

mio = 1000000

condition = 4 * mio

fibo_lst = [1, 2] # 1 and 2 are already in here, because i know that this are fibonacci numbers

for i in range(100):
    term = fibo_lst[i] + fibo_lst[i+1] # each new term is generated by adding the previous two terms
    if term <= condition:
        fibo_lst.append(term)
    else:
        break

# find even numbers

even_numbers_lst = []

for number in fibo_lst:
    if number % 2 == 0:
        even_numbers_lst.append(number)

print(f"This is our fibonacci list: {fibo_lst}")
print(f"This are the even numbers: {even_numbers_lst}")
print(f"The sum of all even numbers is: {sum(even_numbers_lst)}")